var friends = require('../data/friends.js');


//Sets the exports object to a function
module.exports = function(app){

  // API GET Requests
  app.get('/api/friends', function(req, res){
    res.json(friends);
  });

  app.post('/api/friends', function(req, res){

    var perfectFit = {
      name: "",
      photo: "",
      // 10 questions 10 friends = 10 * 10 =1,000
      finalPiece: 1000
    };

    var userInput = req.body;
    var userName = userInput.name;
    var userPhoto = userInput.photo;
    var userScores = userInput.scores;

    var totalDifference = 0;

    for  (var i = 0; i < friends.length; i++) {

      console.log(friends[i].name);
      totalDifference = 0;

      for (var j = 0; j< friends[i].scores[j]; j++){

        // Scores based on compatibility generated by mathematically formula
        // The abs() method returns the absolute value of a number
        totalDifference += Math.abs(parseInt(userScores[j]) - parseInt(friends[i].scores[j]));

        if (totalDifference <= perfectFit.finalPiece){

          // Reset the perfectFit to be the new friend.
          perfectFit.name = friends[i].name;
          perfectFit.photo = friends[i].photo;
          perfectFit.finalPiece = totalDifference;
        }
      }
    }
    // Save User Info to DB
    friends.push(userInput);

    // Returns a JSON with the user's perfectFit.
    res.json(perfectFit);
  });
};